/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as DotwellKnownSplatRouteImport } from './routes/[.]well-known/$'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUploadRouteImport } from './routes/_authenticated/admin/upload'
import { Route as AuthenticatedAdminRunsRouteImport } from './routes/_authenticated/admin/runs'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from './routes/[.]well-known/mcp/server-card[.]json'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.]well-known/agent-skills/index[.]json'
import { Route as DotwellKnownAgentSkillsQuerySwedishAiSKILLDotmdRouteImport } from './routes/[.]well-known/agent-skills/query-swedish-ai/SKILL[.]md'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotwellKnownSplatRoute = DotwellKnownSplatRouteImport.update({
  id: '/.well-known/$',
  path: '/.well-known/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUploadRoute =
  AuthenticatedAdminUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRunsRoute = AuthenticatedAdminRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/.well-known/mcp/server-card.json',
    path: '/.well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentSkillsQuerySwedishAiSKILLDotmdRoute =
  DotwellKnownAgentSkillsQuerySwedishAiSKILLDotmdRouteImport.update({
    id: '/.well-known/agent-skills/query-swedish-ai/SKILL.md',
    path: '/.well-known/agent-skills/query-swedish-ai/SKILL.md',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/runs': typeof AuthenticatedAdminRunsRoute
  '/admin/upload': typeof AuthenticatedAdminUploadRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/.well-known/agent-skills/query-swedish-ai/SKILL.md': typeof DotwellKnownAgentSkillsQuerySwedishAiSKILLDotmdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/api/mcp': typeof ApiMcpRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/runs': typeof AuthenticatedAdminRunsRoute
  '/admin/upload': typeof AuthenticatedAdminUploadRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/.well-known/agent-skills/query-swedish-ai/SKILL.md': typeof DotwellKnownAgentSkillsQuerySwedishAiSKILLDotmdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/runs': typeof AuthenticatedAdminRunsRoute
  '/_authenticated/admin/upload': typeof AuthenticatedAdminUploadRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/.well-known/agent-skills/query-swedish-ai/SKILL.md': typeof DotwellKnownAgentSkillsQuerySwedishAiSKILLDotmdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/.well-known/$'
    | '/admin'
    | '/api/mcp'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/admin/documents'
    | '/admin/runs'
    | '/admin/upload'
    | '/admin/'
    | '/.well-known/agent-skills/query-swedish-ai/SKILL.md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/.well-known/$'
    | '/api/mcp'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/admin/documents'
    | '/admin/runs'
    | '/admin/upload'
    | '/admin'
    | '/.well-known/agent-skills/query-swedish-ai/SKILL.md'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/.well-known/$'
    | '/_authenticated/admin'
    | '/api/mcp'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/runs'
    | '/_authenticated/admin/upload'
    | '/_authenticated/admin/'
    | '/.well-known/agent-skills/query-swedish-ai/SKILL.md'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownSplatRoute: typeof DotwellKnownSplatRoute
  ApiMcpRoute: typeof ApiMcpRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute
  DotwellKnownAgentSkillsQuerySwedishAiSKILLDotmdRoute: typeof DotwellKnownAgentSkillsQuerySwedishAiSKILLDotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/$': {
      id: '/.well-known/$'
      path: '/.well-known/$'
      fullPath: '/.well-known/$'
      preLoaderRoute: typeof DotwellKnownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/upload': {
      id: '/_authenticated/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AuthenticatedAdminUploadRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/runs': {
      id: '/_authenticated/admin/runs'
      path: '/runs'
      fullPath: '/admin/runs'
      preLoaderRoute: typeof AuthenticatedAdminRunsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-skills/query-swedish-ai/SKILL.md': {
      id: '/.well-known/agent-skills/query-swedish-ai/SKILL.md'
      path: '/.well-known/agent-skills/query-swedish-ai/SKILL.md'
      fullPath: '/.well-known/agent-skills/query-swedish-ai/SKILL.md'
      preLoaderRoute: typeof DotwellKnownAgentSkillsQuerySwedishAiSKILLDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminRunsRoute: typeof AuthenticatedAdminRunsRoute
  AuthenticatedAdminUploadRoute: typeof AuthenticatedAdminUploadRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminRunsRoute: AuthenticatedAdminRunsRoute,
  AuthenticatedAdminUploadRoute: AuthenticatedAdminUploadRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownSplatRoute: DotwellKnownSplatRoute,
  ApiMcpRoute: ApiMcpRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  DotwellKnownAgentSkillsQuerySwedishAiSKILLDotmdRoute:
    DotwellKnownAgentSkillsQuerySwedishAiSKILLDotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
